// This file contains mock data for the application
// In a real app, this would come from your database

export const initialRoutes = [
  {
    id: "route1",
    name: "North Route",
    assignedTrucks: ["truck1", "truck3"],
    stops: [
      {
        id: "stop1",
        customerName: "John Smith",
        address: "123 Main St, Anytown, USA",
        phone: "555-123-4567",
        mulchType: "Premium Hardwood",
        mulchQuantity: 10,
        spreadRequested: true,
        paid: true,
        status: "delivered",
        assignedTruck: "truck1",
        assignedScouts: ["Alex Johnson", "Sam Wilson"],
        scoutRoles: {
          "Alex Johnson": "drop",
          "Sam Wilson": "spread",
        },
        instructions: "Place mulch near the garden in the backyard.",
        hasProblems: false,
        problems: [],
      },
      {
        id: "stop2",
        customerName: "Emily Davis",
        address: "456 Oak Ave, Anytown, USA",
        phone: "555-987-6543",
        mulchType: "Pine Bark",
        mulchQuantity: 5,
        spreadRequested: false,
        paid: true,
        status: "pending",
        assignedTruck: "truck1",
        assignedScouts: ["Alex Johnson"],
        scoutRoles: {
          "Alex Johnson": "drop",
        },
        instructions: "",
        hasProblems: true,
        problems: [
          {
            id: "problem1",
            description: "Customer not home, couldn't access backyard",
            resolved: false,
            createdAt: "2023-04-15T10:30:00Z",
          },
        ],
      },
      {
        id: "stop3",
        customerName: "Michael Johnson",
        address: "789 Pine Rd, Anytown, USA",
        phone: "555-456-7890",
        mulchType: "Premium Hardwood",
        mulchQuantity: 15,
        spreadRequested: true,
        paid: false,
        status: "pending",
        assignedTruck: null,
        assignedScouts: [],
        scoutRoles: {},
        instructions: "Call before arrival",
        hasProblems: false,
        problems: [],
      },
    ],
  },
  {
    id: "route2",
    name: "South Route",
    assignedTrucks: ["truck2"],
    stops: [
      {
        id: "stop4",
        customerName: "Sarah Williams",
        address: "101 Maple Dr, Anytown, USA",
        phone: "555-222-3333",
        mulchType: "Cedar",
        mulchQuantity: 8,
        spreadRequested: false,
        paid: true,
        status: "partial",
        deliveredQuantity: 5,
        assignedTruck: "truck2",
        assignedScouts: ["Chris Taylor"],
        scoutRoles: {
          "Chris Taylor": "drop",
        },
        instructions: "",
        hasProblems: true,
        problems: [
          {
            id: "problem2",
            description: "Not enough mulch on truck, need to return with 3 more bags",
            resolved: false,
            createdAt: "2023-04-15T14:45:00Z",
          },
        ],
      },
      {
        id: "stop5",
        customerName: "Robert Brown",
        address: "202 Elm St, Anytown, USA",
        phone: "555-444-5555",
        mulchType: "Premium Hardwood",
        mulchQuantity: 12,
        spreadRequested: true,
        paid: true,
        status: "delivered",
        assignedTruck: "truck2",
        assignedScouts: ["Chris Taylor", "Jamie Lee"],
        scoutRoles: {
          "Chris Taylor": "drop",
          "Jamie Lee": "spread",
        },
        instructions: "Spread mulch in front flower beds only",
        hasProblems: false,
        problems: [],
      },
    ],
  },
  {
    id: "route3",
    name: "East Route",
    assignedTrucks: ["truck4"],
    stops: [
      {
        id: "stop6",
        customerName: "Jennifer Miller",
        address: "303 Birch Ln, Anytown, USA",
        phone: "555-666-7777",
        mulchType: "Pine Bark",
        mulchQuantity: 7,
        spreadRequested: false,
        paid: false,
        status: "pending",
        assignedTruck: "truck4",
        assignedScouts: [],
        scoutRoles: {},
        instructions: "",
        hasProblems: false,
        problems: [],
      },
    ],
  },
]

export const trucks = [
  {
    id: "truck1",
    driverName: "David Wilson",
    capacity: 50,
    phone: "555-111-2222",
    active: true,
    currentStops: ["stop2"],
    completedStops: ["stop1"],
  },
  {
    id: "truck2",
    driverName: "Lisa Martinez",
    capacity: 40,
    phone: "555-333-4444",
    active: true,
    currentStops: [],
    completedStops: ["stop4", "stop5"],
  },
  {
    id: "truck3",
    driverName: "James Thompson",
    capacity: 60,
    phone: "555-555-6666",
    active: true,
    currentStops: [],
    completedStops: [],
  },
  {
    id: "truck4",
    driverName: "Karen Anderson",
    capacity: 45,
    phone: "555-777-8888",
    active: true,
    currentStops: ["stop6"],
    completedStops: [],
  },
  {
    id: "truck5",
    driverName: "Mark Davis",
    capacity: 55,
    phone: "555-999-0000",
    active: false,
    currentStops: [],
    completedStops: [],
  },
]

export const scouts = [
  "Alex Johnson",
  "Sam Wilson",
  "Chris Taylor",
  "Jamie Lee",
  "Pat Smith",
  "Jordan Brown",
  "Casey Miller",
  "Riley Davis",
  "Taylor White",
  "Morgan Green",
]
